language: php

php:
  - 7.3
  - 7.4

dist: bionic

sudo: true

cache:
  directories:
    - $HOME/.composer/cache

services:
  - postgresql

addons:
  postgresql: '9.6'
  apt:
    packages:
      - postgresql-9.6-postgis-2.4

before_install:
  - sudo mount -o remount,size=50% /var/ramfs
  - phpenv config-rm xdebug.ini

install:
  - composer self-update
  - composer install --prefer-dist --no-interaction

before_script:
  - psql -U postgres -c 'create database taxes'
  - psql -U postgres -d taxes -c 'create extension postgis'
  - php init_db.php

script:
  - vendor/phpunit/phpunit/phpunit --stop-on-error --stop-on-failure
